package patrickstar.com.accountms.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TB_FLAG".
 */
public class tb_flag {

    private Integer _id;
    private String flag;
    private String password;

    public tb_flag() {
    }

    public tb_flag(Integer _id) {
        this._id = _id;
    }

    public tb_flag(Integer _id, String flag, String password) {
        this._id = _id;
        this.flag = flag;
        this.password = password;
    }

    public Integer get_id() {
        return _id;
    }

    public void set_id(Integer _id) {
        this._id = _id;
    }

    public String getFlag() {
        return flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
